version: "3.8"
services:
  librespeed:
    image: linuxserver/librespeed
    container_name: librespeed
    ports:
      - "80:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
      - DISABLE_IPV6=true
      - NGINX_IPV6=0
    networks:
      - no_ipv6
    restart: unless-stopped

networks:
  no_ipv6:
    enable_ipv6: false